 " It's where it all began.

function BasicSettings()
    syntax enable               " enable syntax processing
    set nocompatible            " be iMproved

    " Allow backspacing over everything in insert mode
    set backspace=indent,eol,start
    set ignorecase              " Case insensitive
    
    " Spaces and Tabs
    set tabstop=4               " Number of visual spaces per TAB
    set softtabstop=4           " Number of spaces in tab when editing
    set expandtab               " Tabs are spaces
    set shiftwidth=4

    " Vim UI Config
    set number         " Show line numbers
    set showcmd        " Show command in bottom bar
    set cursorline     " Highlight current line
    set wildmenu       " Visual autocomplete for command menu
    set lazyredraw     " Redraw only when we need to
    set showmatch      " Highlight matching [{()}]

    " Searching
    set incsearch " Search as characters are entered
    set hlsearch  " Highlight matches

    " 设定文件浏览器目录为当前目录  
    set bsdir=buffer  
    " 设置编码  
    set enc=utf-8  
    " 设置文件编码检测类型及支持格式  
    set fencs=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
    
    " Complete options (disable preview scratch window, longest removed to aways show menu)
    set completeopt=menu,menuone

    filetype off                   " required!
    filetype indent on " load filetype-specific indent files
    filetype plugin indent on

    " automatic Dart file type detection
    au BufRead,BufNewFile *.dart set filetype=dart
    "scss,sass
    au BufRead,BufNewFile *.scss set filetype=scss
    au BufRead,BufNewFile *.sass set filetype=scss

    "let skim use slim syntax
    au BufRead,BufNewFile *.skim set filetype=slim
endfunction

function KeybindingsRemapping()
    let mapleader=","
    let g:mapleader=","

    " Movement
    "" Move vertically by visual line 
    nnoremap j gj 
    nnoremap k gk

    map <leader>s :w<CR>  
    vmap <leader>x :!pbcopy<CR>  
    vmap <leader>c :w !pbcopy<CR><CR> 
endfunction

" It's where it all beagn.
function Main()
    call BasicSettings()
    call KeybindingsRemapping()
endfunction

call Main()
